### Get Feed
GET {{apiBase}}/feed

### Create subscription
POST {{apiBase}}/subscription
Content-Type: application/json

{
  "name": "test subscription",
  "url": "http://some.url/rssfeed.xml"
}

### Create focus without list
POST {{apiBase}}/focus
Content-Type: application/json

{
  "name": "focus-1",
  "counter": 1,
  "total": 12,
  "subscription": {
    "id": 1
  }
}

### Create focus with list
POST {{apiBase}}/focus
Content-Type: application/json

{
  "name": "focus-with-list",
  "phrases": [
    "aaa",
    "bbb"
  ],
  "subscription": {
    "id": 1
  }
}

### Get all subscriptions
GET {{apiBase}}/subscription

### Get subscription No.1
GET {{apiBase}}/subscription/1

### Get focus feeds
GET {{apiBase}}/focus/1/feeds

### Manual kick off scheduler
POST {{apiBase}}/system/execute-scheduler

### Manual kick off indexing service
POST {{apiBase}}/system/index-program

### Manual kick off indexing service
POST {{apiBase}}/system/index-anison

### Cancel
GET {{apiBase}}/system/cancel/86bec58f-bfae-489e-adff-a2dfe3f18776

### Work
POST {{apiBase}}/work
Content-Type: application/json

{
  "name": "ABC",
  "workMetaList": [
    {
      "key": "aaa",
      "value": "bbb"
    },
    {
      "key": "ccc",
      "value": "ddd"
    }
  ]
}