### Get Feed
GET http://localhost:8081/api/v1/feed

### Create subscription
POST http://localhost:8081/api/v1/subscription
Content-Type: application/json

{
  "name": "test subscription",
  "url": "http://some.url/rssfeed.xml"
}

### Create focus without list
POST http://localhost:8081/api/v1/focus
Content-Type: application/json

{
  "name": "focus-1",
  "counter": 1,
  "total": 12,
  "subscription": {
    "id": 1
  }
}

### Create focus with list
POST http://localhost:8081/api/v1/focus
Content-Type: application/json

{
  "name": "focus-with-list",
  "phrases": [
    "aaa",
    "bbb"
  ],
  "subscription": {
    "id": 1
  }
}

### Get all subscriptions
GET http://localhost:8081/api/v1/subscription

### Get subscription No.1
GET http://localhost:8081/api/v1/subscription/1

### Get focus feeds
GET http://localhost:8081/api/v1/focus/1/feeds

### Manual kick off scheduler
POST http://localhost:8081/api/v1/system/execute-scheduler